# Generated by Django 4.1.5 on 2023-01-24 20:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/user.jpg', upload_to=accounts.models.CustomUser.image_upload_to),
        ),
    ]
