# Generated by Django 4.1.5 on 2023-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='image_profile/no_image.jpg', upload_to='image_profile'),
        ),
    ]
