# Generated by Django 4.1.5 on 2023-01-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='image_profile/user.jpg', upload_to='image_profile'),
        ),
    ]
